# -*- mode: ruby -*-
# vi: set ft=ruby :

BASE_UBUNTU_BOX_NAME = 'precise64'
BASE_UBUNTU_BOX_URI = 'http://files.vagrantup.com/precise64.box'

Vagrant.configure('2') do |config|
  config.vm.define :elk do |elk|
    elk_ip = '11.0.1.7'
    elk.vm.provider :virtualbox do |vb|
      vb.name = "elk"
      vb.customize ['modifyvm', :id, '--memory', '1024']
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
    elk.vm.box = BASE_UBUNTU_BOX_NAME
    elk.vm.box_url = BASE_UBUNTU_BOX_URI
    elk.vm.network :private_network, ip: elk_ip
    elk.vm.hostname = 'elk'
    elk.vm.synced_folder "../resources", "/home/vagrant/resources", create: true
    elk.vm.provision "shell", path: "provision.sh", privileged: false
  end
end